version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
        name: Install Dependencies
        command:  yarn install
      - run:
        name: Build App
        command: yarn build
workflows:
  version:  2
  build_and_test:
    jobs:
      - build
