
version: 2


jobs:
  build:
    docker:
      - image: cimg/node:18.16.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}

      - run: 
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
 
  test_and_lint:
    docker:
      - image: cimg/node:18.16.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Prettier
          command: yarn pretty
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit Tests
          command: yarn test --coverage

  deploy:
    docker:
      - image: cimg/node:18.16.0

    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}

      - run: 
          name: Build App
          command: yarn build

      - save_cache:
          paths:
            - ./build
          key: app-build-cache-{{ .Branch }}

      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site 0ad85f80-e847-42d1-9d09-2d60f27fe33a --auth nfp_9U49a7JprWL5rKEEnUoTEHTaJJEpyUL25d03 --prod --dir=build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_and_lint:
          requires:
            - build
      - deploy:
          requires:
            - test