version: 2.1
orbs:
    node: circleci/node@4.7
jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    parallelism: 5
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: mkdir ~/junit
      - run:
          name: Test application
          command: |
              TEST=$(circleci tests glob "src/__tests__/*.tsx")
              echo "$TEST" | circleci tests run --command="xargs yarn test" --split-by=timings
      - run:
          command: cp junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main