jobs:
  build:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: yarn install
  test:
    docker:
      - image: cimg/base:2023.06
    steps:
      - checkout
      - run: yarn test --coverage
workflows:
  build_and_test:
    jobs:
      - build
      - test